NixOS/nixos-search

src/ElasticSearch.elm

switching to wildcard query

---

src/ElasticSearch.elm

Hide details when clicked on result row again

---

elm.json
src/Page/Options.elm
src/Page/Packages.elm
src/index.scss

package and option detailed view

---

src/ElasticSearch.elm

preserving item displaying details on page refresh

---

src/ElasticSearch.elm
src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Route.elm

Pagination of search results

---

src/ElasticSearch.elm
src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Route.elm
src/index.scss

Select channels one which to search

---

scripts/import-channels-into-elasticsearch

index as keywords

---

src/ElasticSearch.elm

implement NotAsked, Error and empty search result view

---

scripts/import-channels-into-elasticsearch

So we can aggregate on eg `haskellPackages`

Add top-level attrset to package documents

---

.github/workflows/cron.yml
scripts/import-channel

run import-channel every hour for last 3 channels

---

scripts/import-channel
src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

use one index per channel

---

src/Main.elm
src/index.js
src/index.scss

adding a footer and a thank you to bonsai

---

scripts/import-channel
src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm
src/index.js

reduce the platform list and add platform link to hydra

---

src/Search.elm

Better network error description

---

src/Search.elm

Reload search results on channel change

---

scripts/import-channel
src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm
src/index.js

* adds `--force` flag to import-channel script to force index recreation
fixes #72

Provide correct link to hydra job or if exists build

---

src/Main.elm
src/index.scss

and that there is a nice way back to main website
also the navigation is now the same hight as on nixos.org
fixes #59

Make sure that we dont trap users on search.nixos.org

---

scripts/import-channel

Nix language primitives are luckily the same as in JSON

---

src/Search.elm

problem with pagination when a number of items in result matches the display size

---

src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

Fixes wonky selection of item in search result

---

src/Search.elm
src/index.scss

nicer loading spinner

---

src/Main.elm
src/index.html

and also improve on window titles for other pages
fixes #93

Fix title of the app before it loads

---

src/Main.elm
src/Search.elm
src/index.scss

also fixes problem showing result when query is empty string
fixes #92

List channel as button group

---

.gitignore
README.md
elm.json
scripts/import-channel
scripts/packages-config.nix
src/Page/Packages.elm
src/Search.elm
src/index.js

#62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/102)

improve packages search query

---

.github/workflows/cron.yml
.github/workflows/main.yml
.gitignore
import-scripts/import_scripts/channel.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/108)

Fix cron workflow

---

src/Main.elm

fixes #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/111)

add burger icon to show collapsed navbar when on mobile

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/112)

Some UX fixes for showing suggestions

---

src/Page/Options.elm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/113)

Pointing to correct branch for different channels

---

src/Search.elm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/116)

dont show browser autocomplete for query input

---

src/Main.elm
src/Search.elm

fixes #124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/126)

Better define the page we are on

---

src/Search.elm

fixes #123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/127)

change channel order

---

src/Search.elm

fixed #121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/128)

don't show spinner when empty query is submitted

---

src/Search.elm
src/index.scss

fixes #118
fixes #122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/129)

show suggestions loading spinner the moment a user starts typing

---

src/Page/Packages.elm

fixes #114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/130)

Adjust ranking of should_match_bool_prefix queries

---

src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Route.elm
src/Search.elm

fixes #119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/133)

Allow to show results alphabetically

---

import-scripts/import_scripts/channel.py

fixes #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/139)

Always use "nixos-*" channels to look up for builds

---

.github/workflows/cron.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/140)

Use nix to install awscli

---

src/Main.elm

fixes #138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/144)

add link to issues tracker

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

fixes #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/145)

search on multiple fields not just package_attr_name or option_name

---

src/Page/Packages.elm

fixed #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/146)

add longDescription to the list of fields we search over

---

src/Page/Options.elm
src/Page/Packages.elm

fixes #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/155)

allways display default value for fields in result details

---

default.nix

fixes #157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/166)

for node-sass xcodebuild is needed on darwin

---

flake.lock
flake.nix
overlay.nix

It required to also expose the devShell output so I did a bit of
simplification in the flake setup.

add support for `nix develop`

---

.github/workflows/cron.yml
.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/169)

adding cachix to speed up the builds

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

fixes #156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/168)

rework ranking queries

---

src/Search.elm

fixes #171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/172)

using whitespace analyzer and not the default one

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/174)

using whitespace as analyzer reduces too much the matched items

---

src/Main.elm
src/Search.elm

fixes #177 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/178)

when wrong channel is selected (via url) show error

---

src/Page/Packages.elm

fixes #181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/182)

maintainer.name field can also be null

---

src/assets/desc-search-options.xml
src/assets/desc-search-packages.xml
src/index.html
webpack.config.js

Add OpenSearch specifications for both packages and options.

---

src/Page/Packages.elm

fixes #193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/194)

in older channels email was conditional

---

src/Search.elm

At the same time i'm removing all of the fuzziness.
fixes #191 
fixes #187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/195)

By mistake the default analyzer was used for query

---

import-scripts/import_scripts/channel.py

\cc #204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/205)

20.09 -> nixos-20.09beta and unstable -> nixos-21.03pre

---

import-scripts/import_scripts/channel.py

closes: https://github.com/NixOS/nixos-search/issues/204
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/212)

point to release prefix for 20.09 channel

---

.github/workflows/cron.yml
.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/227)

update github actions

---

src/Main.elm

Discard effects when routing only query params

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

Fix links to github sources

---

import-scripts/import_scripts/channel.py
import-scripts/poetry.lock
import-scripts/pyproject.toml

Add retry to parts of the import script which were failing from time to time

---

src/Page/Packages.elm

Fixes support for packages with multiple homepage entries.

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm

closes https://github.com/NixOS/nixos-search/issues/231

Implement scroll to package

---

src/Search.elm

closes #235
- `add` links to documentation
- `request` links to github issue template

Add package / request package link when no results

---

src/Page/Packages.elm

Version should not be shown if it is empty

---

src/Search.elm

Lowercase the query before using it in elasticsearch query.
Fixes #285

Search should be case sensitive

---

flakes/manual.toml

Add sops-nix to flakes

---

flakes/manual.toml

Remove sops-nix flake

---

flakes/manual.toml

Kalker/kalk is a calculator with math syntax that supports user-defined variables and functions, complex numbers, and estimation of derivatives and integrals.
https://github.com/PaddiM8/kalker

Add kalker to the flakes index

---

.github/workflows/cron-nixpkgs.yml
src/Search.elm

cc: @garbas @ysndr @jonringer @nrdxp

release: 21.05 -> 21.11

---

.github/workflows/cron-flakes.yml
.github/workflows/cron-nixpkgs.yml
flake.nix
overlay.nix

The package now has the same name as the `app` and the command (`bin/flake-info`).

flake, overlay: Rename package to `flake-info`

---

flake-info/src/data/export.rs

Print pandoc error rather than panic-ing

---

src/Page/Options.elm
src/Page/Packages.elm

Closes #366
@tomberek is that what you had in mind?

Better naming for flake attributes

---

flakes/manual.toml

flakes: add weblate

---

src/Main.elm

Also ignore installDetail state

---

flake-info/src/bin/flake-info.rs

https://github.com/NixOS/nixos-search/runs/4886414453?check_suite_focus=true#step:7:15
https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations

Print underlying serialisation errors

---

flakes/manual.toml

Here is the project: https://gitlab.com/simple-nixos-mailserver/nixos-mailserver

Add nixos-mailserver to the flakes index

---

.github/workflows/check-flake-files.yml

Resolves #430 (and closes #356)

Add github action to check flake groups

---

.github/actions/common-setup/action.yml
.github/workflows/check-flake-files.yml
.github/workflows/frontend.yml
.github/workflows/import-flakes.yml
.github/workflows/import-nixpkgs.yml

All our actions use the same setup.
To make updating easier I implemented a composite action that can be reused by all other actions
(also includes adaptions for the check implemented in #432)

Use composite action to reuse setup steps

---

flakes/manual.toml

Adding the following flake repos:
- stream-alert-bot
- python-trovo
- multifirefox

Adding my repos to public flakes

---

flake-info/README.md

flake-info: update README

---

flakes/manual.toml

flakes/manual: add hydra

---

README.md

Add additional details on how to install and deploy a local development server.

Update Development section in README.md

---

.github/workflows/frontend.yml

Fixes https://github.com/NixOS/nixos-search/issues/434 maybe
My mailbox be like

Make the Netlify bot quieter

---

flakes/manual.toml

https://github.com/input-output-hk/haskell.nix

Add `haskell.nix`

---

README.md
flake-info/README.md
flake-info/src/data/flake.rs
flake-info/src/data/source.rs
frontend/src/Page/Packages.elm
frontend/src/Search.elm

Add support for sourcehut links

---

frontend/src/Page/Packages.elm

Fixes https://github.com/NixOS/nixos-search/issues/524

Show nix-shell instructions first instead of NixOS Configuration

---

flake-info/src/commands/flake_info.nix

Unblocks https://github.com/NixOS/nixos-search/pull/500#issuecomment-1240709135

Allow `modulesPath` in NixOS modules

---

frontend/src/Search.elm

Fixes https://github.com/NixOS/nixos-search/issues/537 maybe.

Fix wildcard search

---

flakes/manual.toml

Adds a flake I have created and am maintaining which packages https://github.com/mickael-kerjean/filestash nicely.

Add filestash-nix to the flakes index

---

frontend/src/Main.elm

Rename "Options" link to "NixOS Options"

---

flakes/manual.toml

Add to the manual sources Hyprwm/Hyprland (https://github.com/hyprwm/Hyprland)

Adds Hyprland

---

flake-info/src/bin/flake-info.rs

Make the exports lazy using a closure, so that we can abort early if the index exists before doing the expensive work.
Raise an error if neither `--json` nor `--push` is specified.
Flakes are staying strict for now because determining the index name is too tightly coupled with the actual exports.

flake-info: abort early if index exists

---

.github/actions/common-setup/action.yml
.github/workflows/update-flake-lock.yml

The new release addresses the issue with Nix 2.14.
https://github.com/cachix/install-nix-action/releases/tag/v20

.github: bump install-nix-action

---

frontend/src/Main.elm

Fixes https://github.com/NixOS/nixos-search/issues/661

frontend: show query in title

---

flake-info/assets/data/docbook-reader/citerefentry-to-rst-role.lua
flake-info/assets/data/myst-reader/roles.lua
flake-info/default.nix
flake-info/src/data/pandoc.rs

Continuation of https://github.com/NixOS/nixos-search/pull/669

Bundle pandoc filters

---

flake.lock
flake.nix

Update infra repo reference

---

.github/actions/common-setup/action.yml
.github/workflows/build-flake-info.yml
.github/workflows/check-flake-files.yml
.github/workflows/import-to-elasticsearch.yml

ci: jq is already part of ci environment

---

frontend/src/Search.elm

About the commit length chosen: This is what git currently does for nixpkgs. The exact value is dynamic: https://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-a/21015031#21015031

frontend: Show current nixpkgs commit

---

frontend/src/Search.elm

frontend: Show nixpkgs tree instead of commit

---

flakes/manual.toml

flakes: readd microvm.nix

---

flakes/manual.toml

This Repository contains the Flake of the Programm "Solaar". Its a Logitech Driver and config tool for Linux.

Add Solaar-Flake

---

flake-info/README.md

Update wiki link to the official wiki

update wiki link

---

flakes/manual.toml

Numen[1] is a voice control for computing without a keyboard
cc: @anpandey
[1] https://git.sr.ht/~geb/numen

Add numen-nix to index

---

flakes/manual.toml

We've been accepted to nix-community, yay!
https://github.com/orgs/nix-community/discussions/1627

Update owner for autofirma-nix flake

---

frontend/src/Search.elm

Reported in https://github.com/NixOS/nixpkgs/issues/375410#issuecomment-2605923513
CC: @SigmaSquadron

fix: update packaging request template url

---

flakes/manual.toml

https://github.com/kashw2/bitbucket-runner-nix

add github:kashw2/bitbucket-runner-nix to flake index

---

frontend/src/Page/Packages.elm

packages: make teams prettier

---

frontend/src/index.scss

display 'show more' even without hover

---

README.md

Add `yarn install` to development instructions

---

flake-info/src/data/export.rs
flake-info/src/data/import.rs
flake-info/src/data/utility.rs

explaining the difference between 'import' and 'export'

Remove unused utility, add some code comments

---

flakes/manual.toml

A collection of Terraform versions that are automatically updated.

flake-list: Add stackbuilders/nixpkgs-terraform flake

---

flakes/manual.toml

Hi,
the purpose of this PR is to add the [opnix](https://github.com/brizzbuzz/opnix) flake

chore: add opnix flake repo

---

frontend/src/List/Extra.elm
frontend/src/Page/Flakes.elm
frontend/src/Page/Options.elm
frontend/src/Page/Packages.elm
frontend/src/Search.elm

Draft because it depends on #972

Further code simplifications

---

frontend/src/List/Extra.elm
frontend/src/Search.elm

Support negative keywords in queries

---

.github/workflows/frontend.yml

And in that case, not only build but actually deploy

allow manually dispatching a frontend deploy

---

.github/workflows/import-to-elasticsearch.yml

FIXES: #1040
