NixOS/nixos-search

scripts/import-channels-into-elasticsearch

otherwise elasticsearch will performs stemming which removes important
information:
Example:
Name: "nixpkgs-review"
Elasticsearch with 'text' mapping: ["nixpkgs", "review"]
At the moment searching for `*nixpkgs-review*` will return no results.

import name/homepage as keyword

---

scripts/import-channels-into-elasticsearch
src/ElasticSearch.elm
src/Page/Packages.elm

So searching `requests` from `python3Packages.requests` can become a cheap prefix search instead of leading wildcard which is horrible for performance.

Use a custom attrname analyzer

---

scripts/import-channel
src/Page/Options.elm

* description is now converted to html at import time
* default/example should now realize what is an non-value and what is
"None" (as string) value
fixes #69
fixes #67

Fix how we display default/example/description of an option

---

src/Search.elm

but only if it does not end with ".", since items with "." are partial
names only used to drill down to the actual package/option name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-search/117)

include query item in search suggestions

---

import-scripts/import_scripts/channel.py
src/Page/Options.elm
src/Page/Packages.elm

Links in the search results for NixOS 20.09 started throwing 404
otherwise. Not all channels are being pushed to nixpkgs-channels as
apparently it is being phased out.

Always use NixOS/nixpkgs instead of NixOS/nixpkgs-channels

---

elm.json
src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Route.elm
src/Route/SearchQuery.elm
src/Search.elm

resolves #200
Interpret `+` in seaerch query string as space.
**There is a limitation imposed by elm URL parser** we can't access get the raw urls string even when using `Url.Parser.Query.custom` -- the string argument is already decoded. this means we can't tell if the `+` comes from url or was decoded from percent string (`%2B`). All `+` are replaced with space.
previous PR: https://github.com/NixOS/nixos-search/pull/214

Support search engine escaping of spaces (+)

---

src/Main.elm
src/Route.elm
src/Search.elm

I just removed the `cleanUrl` function and updated all the places I found where `#disabled` fragment was used. I think this is enough to remove the hack. I tested the behavior there are no refreshes going on.

Remove cleanUrl and fragment hack

---

src/Main.elm
src/Page/Options.elm
src/Page/Packages.elm
src/Route.elm
src/Route/SearchQuery.elm
src/Search.elm

The goal of this PR is to unify and simplify routing and types around search logic.

Refactor route structure

---

src/Search.elm

* Declared a variable `latest_stable` pointing to the latest stable channel near channels definition. (Line 293)
* Used the variable on line 124 for `defaultChannel` when unspecified.
This is imho better than only changing the line `Maybe.withDefault "unstable"` to `Maybe.withDefault "20.09"`, because if done this way we would have to change version numbers at two places (Line 124 and the definitions around Line 280)

Closes #220 Latest stable is now the default channel

---

src/index.html

This file seems to be missing since 2020-09-22:
https://web.archive.org/web/20200922051906/https://nixos.org/js/jquery-ui.min.js
As there are no bug reports since then, I think it may be save to remove the reference?

Remove unnecessary jquery-ui reference

---

src/Main.elm
src/Search.elm
src/index.less

resolves #224
TODO:
This changes the way we handle Loading:
- `result : RemoteData` is now source of truth for if we should or should not trigger the search
- `resut = Loading` is set only when right conditions are met (eg term is not empty)
- `Main.elm` queries data only when result state is `Loading`
- Unlike before, we now need to set `Loading` also for pagination. Because of this I made a small layout changes so that pagination is visible even in loading state for better UI.
This PR could be improved further - for instance we can avoid having `prev` button enabled during loading etc. However I didin't want to introduce way too many changes in single PR.

Refactor the loading and request management

---

import-scripts/import_scripts/channel.py

Apparently `isinstance(True, int)` is `True` in Python, and so booleans are rendered as Python values, with a capital letter. I changed the conditions to test against `type(value)` instead.

import-scripts: fix boolean rendering

---

src/Main.elm

Previously, navigating to https://search.nixos.org/ would use history.pushState
to redirect to /packages and add a new entry to the browser history.
This meant that if you pressed the back button, you would navigate back to /
which would of course then redirect to /packages again.
Now history.replaceState is used instead of pushState, so the / history entry
is replaced entirely by a /packages history entry and the back button works.

Fix redirect from / to /packages breaking browser back button

---

import-scripts/import_scripts/nix.py
import-scripts/tests/test_nix.py

Adds escaping of `\` and `"` inside double-quoted strings (see `system.name`), and fixes indentation for double-single-quoted strings and `literalExample`s (see `services.snapper.configs`).

Improve nix.py

---

src/Page/Options.elm
src/Page/Packages.elm
src/index.less

- improves usability with keyboard #258
- improves accessbility
See #259 for other relevant discussion
* * *
* Closes #258 
* Closes #189

Add semanticaly clickable `button` element to result list

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm
src/index.less

This is the quickfix for:
- Click actions propagation
- tiny improvement to visibility of clickable area.
Especially the hover actions will need some additional improvements but I think this might be good enough to unblock the feature.

faceted search trap click

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm
src/Utils.elm
src/index.less

Fixes issue with options result & applies the same more link logic.

Apply "more link" on options and fix CSS issues

---

src/index.less

This partially reverts the change I made in https://github.com/NixOS/nixos-search/pull/262 - the hover action on whole result item. Now the underline hover applies only on new clickable area (button itself).

facet search update item hover interaction

---

src/index.html

This reverts https://github.com/NixOS/nixos-search/commit/4d505f34022154a1f193f012c11eb08d07c90271 and removes only unused dependencies of bootstrap (jquery-ui and font awesome). Responsive parts of bootstrap depends on javascript which itself depends on jQuery. We need to be careful around these areas though because Elm doesn't like when something mutates the dom (causes exceptions in function that applies vdom to the dom). https://github.com/NixOS/nixos-search/issues/266
I think these changes should not conflict with https://github.com/NixOS/nixos-search/pull/261 and thus this patch can be merged while faceted-search is being worked on.

Fix mobile only interactions

---

src/Main.elm

I commonly run into a situation where the burger menu button is being
showed to me but it broke some time ago and doesn't expand the menu
anymore.
Since the snipped was probably mostly 1:1 translated from the old
nixos.org page (where we had more links than just the three we have now)
we can probably just remove it now. It is a net win as the feature was
broken and at least now you can use the website on mobile again.

Remove the defunct "burger menu" and always expand the navigation

---

src/Page/Options.elm
src/Page/Packages.elm
src/Search.elm
src/index.less

This improves the copy/paste experience especially for Options.
- Change title from button to a to make it selectable
- Resurrect `Name` meta for Options
- Make sure this won't break keyboard selection
*This was broken due to support for keyboard navigation (wrapping to button) https://github.com/NixOS/nixos-search/pull/260. Fixed in a way it's still focusable by keyboard as well as selectable**
Resolves #271 #272 #276

Improve copy/paste UX in Options and Packages

---

src/Search.elm

otherwise the query is malformed.
This fixes the bug found by @turboMaCk  in #288.

Filter on buckets only when there is some bucket selected

---

import-scripts/import_scripts/packages-config.nix

Legacy aliases are slated for removal and should not be used.
https://github.com/NixOS/nixos-search/issues/306

Do not show legacy aliases

---

import-scripts/import_scripts/channel.py

Example failed import: https://github.com/NixOS/nixos-search/runs/3176800851?check_suite_focus=true#step:12:304

import-scripts: fix IndexError for options with no declarations

---

src/Search.elm

An old index name was used for flakes causing search results to be incomplete

Fix default group name

---

flake-info/src/bin/flake-info.rs

Currently, imports of groups fail if any flake in the group fails
This PR changes to a fail silent-model where imports succeed as long as some flake succeeds.
We should have a way to notify about failing flakes nevertheless

Don't fail import of groups as long as some imports succeed

---

README.md
flake.nix

I added a flake-info app attribute to the flake.
Given this I could also add some Instructions to add and test user's own flakes

Add flake app and Documentation

---

flake-info/src/bin/flake-info.rs
flake-info/src/data/import.rs

The kind argument was not properly documented (possible options incorrectly listed)
This PR implements clap arg_enum for the Kind type to auto generate options

Convert import::Kind enum to a clap compatible arg_enum

---

flake.nix

This helps promoting Nix best practices.
As pointed out by Yannik Sander, defining the app is redundant because the package of the same name is used automatically.

flake: Remove app

---

README.md

The flake attribute must directly name the app.
Previously, the command failed with:
`error: cannot find flake attribute 'github:nixos/nixos-search#apps.flake'`

Readme: Fix flake-info command

---

flake-info/default.nix
flake-info/src/lib.rs
flake.nix

Flake info and dumps were printed to stderr.
These are now sent as low level logs using `log::trace` and can be optionally enabled
Also bundles pandoc and pandoc variables now for less unrelated errors in nix devShells
Resolves #384

Remove noisy prints to stderr

---

flake.nix

Flake had some regressions w.r.t. the latest rename of the `flake-info` attribute and not exporting the rust stdlib path (for tools like rust-analzer)

Fix/devshell Fixes 

---

flake-info/src/data/export.rs
flake-info/src/data/import.rs

Implements first point as mentioned in #391 to prevent issues with plain maintainer names (#389) from happening
cc. @garbas @ncfavier

Allow plain strings for nixpkgs maintainer fields

---

flakes/manual.toml

https://github.com/fort-nix/nix-bitcoin
`nix-bitcoin` also adds service modules for some apps that are already part of nixpkgs: btcpayserver, electrs, clightning, lnd (among others).

Flakes index: Add nix-bitcoin

---

flake-info/src/data/pandoc.rs

The current check is too restrictive and will not match strings containing only self-closing tags, for example the description of [`time.timeZone`](https://search.nixos.org/options?channel=unstable&show=time.timeZone&from=0&size=50&sort=alpha_asc&type=packages&query=time.timeZone).
This change still only renders about 20% of the NixOS option descriptions. I think it's now complete, i.e. there are no strings not containing `<` that would be substantially changed by the DocBook-to-HTML conversion; I could be wrong though.

Render DocBook strings containing < but not </

---

src/Main.elm

Fixes #403 on the Elm level instead of a workaround as in #404.
Also brings support for native browser navigation

Fix perform deeper equality checks for internal links to the same model

---

src/Main.elm

#406 would unnecessarily reload pages if `show=` was toggled.
The checking function compares pages but the new page will be loading while the old one has results already. Hence also ignore `resultz state.
Sorry @ncfavier to have another PR on the same issue

Ignore result data

---

flake-info/src/commands/flake_info.nix
flake-info/src/data/export.rs
flake-info/src/data/import.rs
src/Page/Options.elm

Support extracting module options defined via flake attr `nixosModule` (see [nix/flake.cc](https://github.com/NixOS/nix/blob/0e90b13ab1df925e549b5d55853b65911b4b40d3/src/nix/flake.cc#L582)).
These options are currently ignored by nixos-search.
`nixosModule` options are now exported with a `flake` attr of the form `[ flake ]` (instead of `[ flake moduleName ]`, which is currently used for options defined via `nixosModules.moduleName`).
This change must also be reflected in the Elm and Rust layers.
Field [flake](https://github.com/NixOS/nixos-search/blob/63846c3e82d7d5f08c44a57347249b897fd44be1/flake-info/src/data/import.rs#L67) of struct `NixOption` currently consists of both a flake and a module name.
@ysndr, @ncfavier, could you have a look at this?
Here's what I'd propose for displaying …

Support flake attr `nixosModule`

---

flakes/manual.toml

I'd also like to add my side project to the index.
Could also be the first example on how to add non-gitlab/github flakes.
Did I understand the readme right, that I *have* to add the `rev` attribute?

flakes: Add sway-timetracker

---

.github/workflows/import-nixpkgs.yml
src/Search.elm

Since it has reached the end of its support lifetime and is [not being updated](https://status.nixos.org/) anymore.

Drop 20.09 channel

---

.github/workflows/import-flakes.yml
.github/workflows/import-nixpkgs.yml

Import failing for a channel/group doesn't mean it will fail for the other channels/groups

CI: don't fail-fast

---

flake-info/src/commands/nixpkgs_info.rs

Since Nix 2.6 (https://github.com/NixOS/nix/pull/5883) nix-env doesn't output the `meta` attribute unless this flag is passed.
Unblocks the import: https://github.com/NixOS/nixos-search/actions/runs/1744880186

Pass --meta to nix-env

---

flake.nix

Allows `nix build .#...` locally to fetch build products from the cache without having to modify `nix.conf`

flake: add nixos-search.cachix.org to substituters

---

.github/workflows/import-nixpkgs.yml
flake-info/src/data/source.rs

The nixpkgs import seems to have intermittent [failures](https://github.com/NixOS/nixos-search/actions/workflows/import-nixpkgs.yml?query=is%3Afailure) (~four~ five in the past week) where the GitHub API returns 403. I think we may be hitting a rate limit of some sort, so this PR
- authenticates to GitHub in workflows using the GITHUB_TOKEN,
- prints the full response text in case of error, and
- sets the user agent to `nixos-search` as requested [here](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required).
Workflow [still running correctly](https://github.com/NixOS/nixos-search/runs/5077730932?check_suite_focus=true).

Authenticate to the GitHub API in nixpkgs workflow

---

src/Page/Packages.elm

I am not a web dev and have no knowledge of Elm beyond hacking this locally on a lazy afternoon. :p
It works but of course I welcome your reviews on code style, validity of the approach, ...
The package details are a bit hard to read :
* names and versions are visually similar to the rest of the text
* hard to distinguish licenses when there is more than one (the coma is buried)
* Homepage and Source are visually similar and too close the the last license (all links)
* depending on the length of the license list, Homepage **and/or** Source can be pushed onto the second line
Last point is really my main complaint with the current display of results.
Sometimes you have Homepage on the first line and Source on the second. Sometimes you have both on the second line.
The unpredictable position …

Improve short package details readability

---

flakes/manual.toml

LINK: https://polymc.org
LINK: https://github.com/PolyMC/PolyMC
Metadata and disabling of `aarch64-darwin` in https://github.com/PolyMC/PolyMC/pull/168

flakes: add PolyMC flake info

---

.github/workflows/check-flake-files.yml
.github/workflows/frontend.yml
.github/workflows/import-flakes.yml
.github/workflows/import-nixpkgs.yml

Flakes don't need a deep clone. Workflows still succeed: https://github.com/NixOS/nixos-search/actions/runs/1910453681 https://github.com/NixOS/nixos-search/actions/runs/1910460271 https://github.com/NixOS/nixos-search/actions/runs/1910476017

CI: do shallow clones

---

.github/workflows/check-flake-files.yml
.github/workflows/frontend.yml
.github/workflows/import-flakes.yml
.github/workflows/import-nixpkgs.yml

I forgot that using `**` in bash requires an option to be enabled.
Alternatively, do we really need to *recursively* look for `.toml` files? Otherwise we could just go with `flakes/*.toml`.
Workflow now succeeds: https://github.com/NixOS/nixos-search/runs/5360158285?check_suite_focus=true

CI: enable globstar

---

.github/workflows/check-flake-files.yml
flake-info/Cargo.lock
flake-info/Cargo.toml
flake-info/src/bin/flake-info.rs
flake-info/src/commands/nix_flake_info.rs
flake-info/src/data/source.rs

flake-info will populate an environment variable with a report for all failed flakes of a group if applicable.
This should help detecting faulty flakes more easily
- adds a `--report` flag to `flake-info group` which will create a report of failed flakes if some flakes of a group fail to evaluate.
- if all flakes fail the process will throw an error as it is more likely that a major issue occured

Add group reports for flake-group check

---

flake.nix

Makes more sense to have the CLI tool as default package.

flake: set flake-info as default package

---

flake-info/src/bin/flake-info.rs
flake-info/src/data/source.rs

Add a subcommand that allows to import nixpkgs from a local repository or archive file
I wanted to have this earlier and #442 brought this back up.
To test changes to nixpkgs (i.e. the all-packages.nix) file, we need to point to an arbitrary source of nixpkgs.
What remains is a way to see changes in a (testing) frontend but that is a separate issue
USAGE:
```
$ nix run github:nixos/nixos-search/cli/nixpkgs-archive-import -- nixpkgs-archive <path-to-archive or folder> [other options]`
```

Import Nixpkgs from path

---

flake-info/.cargo/config.toml
flake-info/Cargo.lock
flake-info/Cargo.toml
flake-info/src/bin/flake-info.rs
flake-info/src/commands/mod.rs
flake-info/src/commands/nix_check_version.rs
flake-info/src/commands/nixpkgs_info.rs

We need at least nix 2.7 (or 2.7pre_old_enough) for the nixpkgs import, so give a helpful error instead of letting nix fail.
It got a bit messy because nix versions aren't quite semver-compliant (there should be a dash before pre) so I had to strip the pre-suffix.

flake-info: enforce minimal nix version

---

.github/workflows/import-to-elasticsearch.yml

Nix 2.8 was released so we don't need nixUnstable anymore.
https://nixos.org/nix/install

Use stable nix

---

flake-info/src/commands/nix_flake_attrs.rs

Makes `nix run nixos-search#flake-info flake ...` succeed with an empty `NIX_PATH`.

flake-info: Stop relying on user's NIX_PATH for flake extraction

---

flake.nix
frontend/src/Search.elm

Display `deprecated` (but not `unmaintained`) channels. Currently this includes 21.11 but not 21.05.

Display deprecated channels

---

flake-info/src/bin/flake-info.rs
flake-info/src/data/export.rs
flake-info/src/elastic.rs
flake-info/src/lib.rs

Avoid panicking if export fails for a single flake, e.g. if Pandoc fails to render the description. (Flake import is currently stuck because of nix-bitcoin...)
Also make sure that `get_flake_info` is only called once per flake.

Don't panic during export

---

flake-info/src/commands/nix_flake_attrs.rs

I think it is surprising that `flake-info` tries to build things in order to index flakes. Hence, forbid IFD.
`--read-only` is for performance, see https://github.com/NixOS/nix/pull/6323
Ping @srid since your flake (emanote) is currently the only one that uses IFD (but note that it fails even with IFD: `error: a 'aarch64-darwin' with features {} is required to build ...`, so it's not indexed currently)
Ping @erikarvstedt because why not

Disallow Import From Derivation in flakes

---

flake-info/src/commands/nix_flake_attrs.rs

For reasons I don't fully understand, some flakes succeed being indexed with `--no-allow-import-from-derivation` but fail if `--read-only` is added. See https://github.com/NixOS/nixos-search/pull/502#issuecomment-1193277053

flake-info: remove `--read-only`

---

README.md
frontend/src/Page/Options.elm
frontend/src/Page/Packages.elm

This allows listing all packages or options of a specific flake.
To test this, compare
- [localhost:3000/flakes/cargo](http://localhost:3000/flakes?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=cargo)
- [search.nixos.org/flakes/cargo](https://search.nixos.org/flakes?channel=unstable&from=0&size=30&sort=relevance&type=packages&query=cargo)
The elasticsearch backend doesn't work properly with hyphens in Flake names:
```bash
queryPackages() {
query=$1
curl -fsS 'https://nixos-search-5886075189.us-east-1.bonsaisearch.net/latest-31-group-manual/_search' \
-X POST -H 'Authorization: Basic ejNaRko2eTJtUjpkczhDRXZBTFBmOXB1aTdYRw==' \
-H 'Content-Type: application/json' \
--data-raw '
{
"query": {
"bool": {
"filter": [ {"term": {"type": {"value": "package", "_name": …
```

Flakes search: Include flake name

---

frontend/src/index.html

Removing a small annoyance.
"Loading" used to show up in discourse links, looking silly.
"Loading" didn't really add information. If it loads slowly or not
at all, the result will be quite obvious, and often the bit that
says "Loading" doesn't even fit in the browser tab label.

Remove Loading from title

---

frontend/src/Page/Packages.elm
frontend/src/Search.elm
frontend/src/index.less

This would close https://github.com/NixOS/nixos-search/issues/508
1. `nix-env` now has a warning associated with it, which explains that it has side-effects which may require cleanup by the user manually after usage like a traditional package manager.
2. NixOS configuration(s) and nix-shell have now got a tab on each package, which explains how to use `environment.systemPackages` or `nix-shell -p`.
1. I have replaced `FromNixOS` and `FromNixpkgs` with `ViaNixOS`, `ViaNixShell` and `ViaNixEnv`
2. I have removed the `$` before every instance of `.terminal` in `frontend/src/index.less` because I was not easily able to case split on imperative cmds like `nix-shell -p` and the code for a NixOS configuration. Instead, `$` has been placed manually into each text field where a command is …

encourage NixOS configuration, nix-shell and discourage nix-env

---

frontend/src/Page/Packages.elm

Fixes https://github.com/NixOS/nixos-search/issues/521

frontend: remove trailing whitespace in installation instructions

---

flake-info/src/commands/flake_info.nix

Having the documentation for `_module.args` in the nixpkgs options is useful, but there's no need to have a copy of it per flake module.
Accidentally fixes https://github.com/NixOS/nixos-search/issues/534

Ignore `_module` options for flakes

---

.github/actions/common-setup/action.yml
.github/workflows/build-flake-info.yml
.github/workflows/check-flake-files.yml
.github/workflows/frontend.yml
.github/workflows/import-to-elasticsearch.yml

Prevents [hitting](https://github.com/NixOS/nixos-search/actions/runs/3345951892/jobs/5542138556#step:4:57) GitHub's API rate limits.
This was removed in https://github.com/NixOS/nixos-search/pull/415 because I didn't understand what it was for.
~N.B. I don't know if accessing `secrets` in the action file works, do we need an `inputs.GITHUB_TOKEN`?~ EDIT: nope, it [doesn't](https://github.com/NixOS/nixos-search/actions/runs/3346133543/jobs/5542554665#step:3:2).
EDIT 2: [works fine now](https://github.com/NixOS/nixos-search/actions/runs/3346157934/jobs/5542610636).

.github: re-add access token

---

frontend/src/Search.elm

Fixes https://github.com/NixOS/nixos-search/issues/537
Now that we're on 7.10 we can enable case-insensitive wildcard search.

Fix wildcard search (for real this time)

---

flakes/manual.toml

- PolyMC was marked as insecure in nixpkgs after one of its maintainers went rogue, removing all of the other maintainers
- The removed maintainers made a fork, [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher)
- As by design PolyMC downloads code from a server (now controlled by that maintainer), [this warranted replacing PolyMC in nixpkgs with its successor, prismlauncher](https://github.com/NixOS/nixpkgs/pull/196624#issuecomment-1284449789)
This PR makes the same change to the flakes search index that has already been made in nixpkgs.
- https://github.com/NixOS/nixpkgs/issues/196460
- https://github.com/NixOS/nixpkgs/pull/196624
- https://github.com/NixOS/nixpkgs/issues/196480

Replace PolyMC with PrismLauncher in the index

---

flake-info/src/data/export.rs
flake-info/src/data/import.rs

Licenses in nixpkgs aren't required to contain a `fullName` *or* a `shortName` field: for example, [altermime](https://github.com/NixOS/nixpkgs/blob/758e5af4cd3e9d73d4f94fec1e2b02130e04c727/pkgs/tools/networking/altermime/default.nix#L29) only has a `fullName` while [getLicenseFromSpdxId](https://github.com/NixOS/nixpkgs/blob/758e5af4cd3e9d73d4f94fec1e2b02130e04c727/lib/meta.nix#L127) only returns a `shortName` for unknown SPDX IDs. Since no particular format is enforced in nixpkgs, and we want to [be resilient to upstream issues](https://github.com/NixOS/nixos-search/issues/391), we should make both fields optional for now.

Give more license to the license field

---

frontend/src/Search.elm
frontend/src/index.scss

People that navigate the web using a screenreader use headings to navigate faster on a website.
With this change, blind users can more easily go to the search results.

Improve accessibility for screenreader users

---

flakes/manual.toml

Hi, @ncfavier, @figsoda ! I'd like to add a flake with ~40K VS Code extensions and ~3K Open VSX extensions that get updated daily.

add nix-vscode-extensions

---

flake-info/src/data/export.rs
flake-info/src/data/import.rs
flake-info/src/data/utility.rs

nixpkgs currently [defines](https://github.com/NixOS/nixpkgs/blob/6877dd6b9e85d2d0d538042db3f8d20eac6865a2/lib/meta.nix#L72-L85) three ways of specifying elements of `meta.{platforms,badPlatforms}`:
1. as a string; this is okay
2. as a *pattern*, which is an attribute set meant to match a platform's `parsed` field (or possibly in the future an entire platform, see https://github.com/NixOS/nixpkgs/pull/212939). This has apparently been a thing for a long time but wasn't used until [about a week ago](https://github.com/NixOS/nixpkgs/pull/210259). For now, just skip them without causing an error. Later, maybe figure out a way to display them properly.
3. as a function platform → bool; this causes nix-env to emit `null` which is [not …

flake-info: support platform patterns

---

flake-info/default.nix
flake-info/src/bin/flake-info.rs
flake.nix

Fixes https://github.com/NixOS/nixos-search/issues/585
The feature is broken in two different ways that, by luck, cancel each other out (well, three if you count the above issue).
- The branches of the `map_or_else` call [here](https://github.com/NixOS/nixos-search/blob/d04f341a5d3b4a865249d743b80a198f55729473/flake-info/src/bin/flake-info.rs#L419-L427) are swapped, so that we only raise an error if the channel **is found** in `NIXOS_CHANNEL`
- ... luckily the `find` call just above it is also broken: we're matching a `channel` of the form `XX.YY` against a `branch` attribute that looks like `nixos-XX.YY`, so it never finds anything.
I don't think we should have this feature at all since AFAICT it serves no real purpose and would prevent people from running flake-info on older nixpkgs …

flake-info: remove broken `NIXOS_CHANNELS` check

---

frontend/src/Main.elm

Fixes https://github.com/NixOS/nixos-search/issues/594
Follow-up to https://github.com/NixOS/nixos-search/pull/562: `from` was carried over both from the search args (which this PR fixes) and from the model (which the previous PR fixed)

frontend: reset `from` and `buckets` when changing pages

---

flake-info/default.nix
flake-info/src/data/pandoc.rs
flake.lock
flake.nix

Update nixpkgs and adapt to the changes in https://github.com/NixOS/nixpkgs/pull/208762: the link-manpages filter is now generated using Nix.
NixOS options already have manpage links in `options.json`, but we should still keep the filter for flakes. The filter does not add [double links](https://github.com/NixOS/nixpkgs/pull/208762/files#diff-69364cc9f324cdeb2698134a3cb943a44b656981bfc943b7bec030df45e288dfR17-R20) any more so this is harmless.

flake-info: update manpage filter

---

frontend/src/Page/Packages.elm

also highlight the command name
Note: This is a drive-by change done in the browser, sorry if this breaks things. Feel free to make fix-ups as needed.

refine the warning on using `nix-env`

---

frontend/src/Page/Packages.elm
frontend/src/index.scss

rename to "programs provided", since where they are provided is an implementation detail irrelevant to users of `nix-shell -p`.
I'd actually prefer to list provided programs above the fold, because that is what users will care about much more than e.g. outputs of the derivation, which is also an implementation detail.
Related: https://github.com/NixOS/nixos-search/issues/542

move programs to the top of the metadata display

---

flake-info/src/data/pandoc.rs

E.g. [weechat](https://search.nixos.org/packages?channel=unstable&show=weechat&from=0&size=50&sort=relevance&type=packages&query=weechat)'s long description

Auto-link bare URIs in MarkDown

---

.github/actions/common-setup/action.yml
.github/workflows/update-flake-lock.yml

2.14 has a bug related to profile locations that breaks nix-env, which in turn breaks cachix. Pin to 2.13 for now.
More info at https://github.com/NixOS/nixpkgs/pull/218858#issuecomment-1448758169

.github: pin nix 2.13

---

frontend/src/Search.elm

Follow the same default title as when opening a package request from GitHub directly.

Follow title convention for package requests

---

frontend/src/Search.elm

This improvement creates extra "variants" for the wildcard search allowing us to search (fx) for `nodejs_18` and get the result `nodejs-18_x`. Should resolve #644 that also contains more examples of these punctuation cases.

Improve search results with underscore and dash/hyphen package names

---

frontend/src/Main.elm
frontend/src/Search.elm
frontend/src/index.html
frontend/src/index.scss

This pull request fixes some of the major issues related to Accessibility, it also resolves #332.
The fix handles all pages (packages, options, flakes):
- Use `button` instead empty `a` tag for pagination, also fixes contrast-ratio.
- Added logo alt and lang
- Accessibility overrides in `frontend/src/index.scss`:
- A better fix for this would be to use a newer version of bootstrap (current using version 2)
Used "chrome lighthouse" and "axe devtools" to measure accessibility, screenshots with before and after:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Accessibility fixes

---

.github/workflows/import-to-elasticsearch.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`set-output` currently triggers a warning and would start failing on June 1st.

.github: remove deprecated `set-output` command

---

flake-info/default.nix
flake-info/src/data/link-manpages.nix

It's being [removed](https://github.com/NixOS/nixpkgs/pull/239636#discussion_r1248903109) from nixpkgs as part of the dedocbookification process. Eventually we'll want to use nixos-render-docs to render options.

Bundle `link-manpages.nix`

---

flake.nix

Following this commit https://github.com/NixOS/nixos-search/commit/1128c8fb69d4a8557baeee13053e7792339554f9,
running `nix develop` would throw an error due to remaining usages of `flake-info.NIXPKGS_PANDOC_FILTERS_PATH` though it has been removed:
```
error: attribute 'NIXPKGS_PANDOC_FILTERS_PATH' missing
at /nix/store/5wfjb864pkb65z8nx6mb7cln12nm1g78-source/flake.nix:103:53:
102|               export RUST_SRC_PATH="${pkgs.rustPlatform.rustLibSrc}";
103|               export NIXPKGS_PANDOC_FILTERS_PATH="${packages.flake-info.NIXPKGS_PANDOC_FILTERS_PATH}";
|                                                     ^
104|               export LINK_MANPAGES_PANDOC_FILTER="${packages.flake-info.LINK_MANPAGES_PANDOC_FILTER}";
```
This PR removes the remaining exports since they aren't used anymore.

Remove remaining usages of NIXPKGS_PANDOC_FILTERS_PATH

---

frontend/src/index.scss

This PR adds a dark theme that is activated if the user has [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) set to dark. The light theme is unchanged, the dark theme has some minor UI tweaks, to make it look better with a darker color scheme. The dark theme also does not have color gradients on some buttons, because I do not like them.
You can try nixos-search with darkmode at [search.wirs.ing](https://search.wirs.ing/).
Some comparison screenshots between dark and light mode
I had to actively fight the ancient bootstrap stylesheet we are using for styling some things. The bootstrap stylesheet is imported from nixos.org but I am pretty sure that it has not been used there for multiple years. As a consequence the CSS here is quite …

Add dark theme

---

COPYING

Fixes #722
This repository has no license on it at the top level. ([The frontend code is MIT licensed](https://github.com/NixOS/nixos-search/blob/744ec58e082a3fcdd741b2c9b0654a0f7fda4603/frontend/package.json#L6))  I copied the license from nixpkgs, which uses the MIT license. If this isn't the license people want to use, let's discuss that here. 
Since this work was done in the context of the NixOS organization, which is dedicated to open source, I think it makes sense for this to have an open source license. I think that the contributors had a reasonable expectation that their work was being done under some open source license, but we should get approvals anyway. If you are okay with the MIT license please respond below:
> I license all of my past contributions to the nixos-search …

add COPYING license under MIT

---

frontend/src/index.scss

This PR implements changes to the dark theme (#730) based on user feedback. A preview deployment is available at [search.wirs.ing](https://search.wirs.ing).
I received the following feedback:
- The header bar should have a different color than the main content
- White text for everything has too much contrast 
- The sort dropdown should have a different background color
- The results do not look like links because they are the same color as the text
- Bad contrast of hovered links
This PR addresses all of these points.
While the result is still not optimal, as now all text is grey, there is no easy fix for this. A better solution would be to redesign [search.nixos.org](https://search.nixos.org) to align its styling more closely with [nixos.org](https://nixos.org), but that would require a …

Improve dark theme

---

flake-info/src/data/import.rs
flake-info/src/data/prettyprint.rs

RFC-166 is merged and is going to be the default style for nixpkgs.
It makes sense to also have the official documentation look the same so people both get used to the style and can copy-paste sensibly formatted code.
The RFC is very long but since we only deal with primitive values here (no lets, functions and whatnot), the change is very easy and only affects lists and attrsets with one item.
The only other rule I can think of that would be required would be the maximum line length, but I'm honestly too lazy and I don't think this rule would apply very often in option defaults/examples.
I also added 2 more minor fixup commits for attrset names with weird characters in them and I reduced the number of clones in the pretty-printer.

flake-info: Adapt RFC-166 style

---

frontend/src/index.scss

close #737 
CC @Aleksanaa
Works on my machine

fix: code block in long description of a package in dark mode

---

frontend/src/index.scss

| Before | After |
| - | - |
| ![Screenshot 2024-04-27 at 18 02 43 (Arc)](https://github.com/NixOS/nixos-search/assets/47499684/cc877d5c-7a6a-4ed1-86d1-794e6e52a238) | ![Screenshot 2024-04-27 at 18 03 01 (Arc)](https://github.com/NixOS/nixos-search/assets/47499684/2dccffe1-843b-40b8-b16f-1ed847f6196a) |
I think the contrast of the logo looks just fine and more recognizable without the filter/invert.

fix: remove filter on header logo

---

frontend/src/index.scss

| Before | After |
| - | - |
| ![Screenshot 2024-04-27 at 17 58 50 (Arc)](https://github.com/NixOS/nixos-search/assets/47499684/7d6ca084-c8dc-4931-86cc-6e87f7f62e44) | ![Screenshot 2024-04-27 at 17 59 05 (Arc)](https://github.com/NixOS/nixos-search/assets/47499684/867cce62-edd0-44d3-866c-48540b6397be) |
Notice how the search / magnifying glass icon is now vertically centered to match the text :)

fix: center magnifying glass / search icon

---

frontend/src/Search.elm

We still use Bonsai, but we proxy it now so the message is misleading since the browser doesn't actually try to access bonsai.

frontend: Remove stray bonsai reference

---

flake-info/src/commands/nix_flake_attrs.rs

Same workaround as in nix-community/nur-packages-template#95 and https://github.com/wegank/nur-packages/commit/631ea9f525ec2ecfb3daf4365cab213b19baa0cf, should hopefully fix the hourly import.

flake-info: drop channels for flake commands

---

frontend/src/Page/Packages.elm

the one you want to click varies in position, which makes it actually take some effort to find each time.
this sorts them so you can get used to clicking in a certain place if you usually use only one architecture

frontend: sort platforms

---

flake.nix

So that `nix develop .#frontend` works out of the box.
(Although I would use `netlify dev` on my machine for the backend redirection...)

flake.nix: fix frontend dev shell

---

frontend/src/Page/Packages.elm

"This package is not available on any platform" is misleading and confusing, so I changed that.
Related https://github.com/NixOS/nixpkgs/issues/270206
Closes https://github.com/NixOS/nixos-search/issues/734

fix: wording when a package has no platforms list

---

frontend/src/Page/Packages.elm

This makes more sense than having nix build, which doesn't really install things

frontend: Suggest nix profile install for flakes installation

---

.github/workflows/check-flake-files.yml
flake-info/README.md
flakes/manual.toml

These public flakes are not indexed on https://search.nixos.org/flakes due to various errors, and can therefore be safely dropped.

flakes: drop problematic sources

---

flakes/manual.toml

https://github.com/ngi-nix/pixelfed has been archived in 2023, since the service is upstreamed.

flakes: drop github:ngi-nix/pixelfed

---

frontend/src/index.scss

Used to look like this on Chrome:
Used to look like this on Firefox:
---
Now looks like this on both:

frontend: Fix magnifying glass position and font

---

frontend/src/Page/Packages.elm

Packages.elm: add missing newline to 'nix-env' tab

---

flakes/manual.toml

agenix is a popular secrets management tool for NixOS.
https://github.com/ryantm/agenix

add agenix

---

flakes/manual.toml

- nixpkgs-esp-dev is a flake for building ESP32 firmware.
- micropython-builder is a flake for building MicroPython, currently only for ESP32.

Added nixpkgs-esp-dev and micropython-builder to flakes index

---

frontend/src/Search.elm

The previous link lands on a mostly-empty placeholder page pointing to a different link.
I've updated it to point directly to the final link in the chain.

fix: Update old link in no results view

---

frontend/src/Page/Options.elm
frontend/src/Page/Packages.elm

We reached both 120k packages and 20k options some time ago:
```bash
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl jq brotli
function parse_unstable_json() {
local url="https://channels.nixos.org/nixos-unstable/$1.json.br"
echo $(curl -L "$url" | brotli -d --stdout | jq "$2")
}
pkg_count=$(parse_unstable_json "packages" ".packages | length")
opt_count=$(parse_unstable_json "options" "length")
echo "{ 'packages': $pkg_count, 'options': $opt_count }" | tr "'" '"'
```
> `{ "packages": 121548, "options": 20197 }`
See:
- #701

chore: bump package and option count

---

flakes/manual.toml

This adds the nixpkgs-ruby flake, which aims to package all ruby versions.
See https://github.com/bobvanderlinden/nixpkgs-ruby

Add nixpkgs-ruby flake

---

flakes/manual.toml

This adds [CertainLach/fleet] to flake sources.
Quote from the repo:
> An NixOS cluster deployment tool.
[CertainLach/fleet]: https://github.com/CertainLach/fleet

Add github:CertainLach/fleet to flake sources

---

flakes/manual.toml

Is there any reason why home-manager is still not in here? I feel like there are a lot of people using it and having it's options listed here could be very helpful

Add home-manager to flake sources

---

flakes/manual.toml

Nix flake for bleeding-edge and unreleased packages (e.g., mesa_git, telegram_git)
Additonally it provides cachyos linux kernel.
@dasJ @Mic92 friendly ping

flake-list: add chaotic nyx flake

---

frontend/config/webpack.common.js

This is a fix to remove the use of `DefinePlugin` with `process.env` as it exposes all env variables in your bundle.
If you inspect `https://search.nixos.org/bundle.js` you will notice all CI env vars are bundled with your app.
```js
n.Main.init({
flags: {
elasticsearchMappingSchemaVersion: parseInt("42"),
elasticsearchUrl:
{
NODE_ENV: "production",
SHELL:
"/nix/store/phqa311klldrcbwid1i22dwnpfc9dnma-bash-5.1-p8/bin/bash",
npm_config_timing: "",
npm_config_access: "",
... 
}.ELASTICSEARCH_URL || "/backend",
```

chore: expose only a set of env variables

---

frontend/src/Page/Packages.elm
frontend/src/index.scss

Fixes #865 (there is no button but it is very easy to copy the list)

Add a section with all maintainer github names

---

frontend/src/Page/Packages.elm

It seems I only tested #878 with packages that have more than one maintainer, but the section is still useful if there is only one maintainer.

Show GH handle for packages with one maintainer

---

frontend/src/Search.elm

packaging_request.md template has been removed from nixpkgs github(https://github.com/NixOS/nixpkgs/tree/master/.github/ISSUE_TEMPLATE) after this PR: https://github.com/NixOS/nixpkgs/pull/391926
Following discussion here: https://github.com/NixOS/nixos-search/pull/881, this removes the now broken link to it from search.nixos.org
CC: @raboof

fix: Remove link to "make a packaging request"

---

frontend/src/Search.elm

When an user searches for a package not already merged it won't be found.
For example:
> https://search.nixos.org/packages?channel=unstable&query=nibbler
Right now it won't find the package, because it hass just been requested.
But it might be useful to the user to quickly check for the status on nixpkgs.
Therefore I Added a link to `nixpkgs/issues?q=PACKAGENAME` in `viewNoResults`.

Suggest to search on nixpkgs issues when nothing is found

---

flake-info/src/data/export.rs
flake-info/src/data/import.rs
flake-info/src/data/utility.rs
flake-info/src/elastic.rs
frontend/src/Page/Packages.elm

Fixes #907
We should get this close with https://github.com/NixOS/nixpkgs/pull/400458.
My lack of experience with rust got me some progress but I couldn't get past this error:
```
flake-info> error[E0277]: the trait bound `export::Maintainer: From<OneOrMany<import::Maintainer>>` is not satisfied
flake-info>    --> src/data/export.rs:387:42
flake-info>     |
flake-info> 387 |                 members: members.map(|m| Maintainer::from(m)),
flake-info>     |                                          ^^^^^^^^^^ the trait `From<OneOrMany<import::Maintainer>>` is not implemented for `export::Maintainer`
flake-info>     |
flake-info>     = help: the following other types implement trait `From<T>`:
flake-info>               `export::Maintainer` implements `From<flake::Flake>`
flake-info> …
```

Add meta.teams support

---

README.md
flake.nix

This is an alternative to #917, using the OpenSearch config from there to build a NixOS configuration for a VM that runs an OpenSearch node exposed to the host on port 9200. The VM run script is exposed via `apps.<system>.opensearch-vm` so you can just `nix run .#opensearch-vm` and get an accessible instance that you can load information into.

Provide VM config for local end-to-end testing

---

flake-info/src/bin/flake-info.rs
flake-info/src/commands/nixpkgs_info.rs
flake-info/src/lib.rs

Alternative to #916, with the additions that:
* When an attribute is provided to `nixpkgs` and `nixpkgs-archive`, `--kind package` is forced.
* The attribute is provided as `--attr <name>` instead of a positional argument. This is to make it easier to add something like `--option` in the future.

flake-info: support importing a single nixpkgs attribute via --attr

---

README.md

Document flake inclusion criteria

---

flake-info/README.md

https://nixos.org/guides/install-nix.html return:
```
Not found
The requested content at /guides/install-nix.html could not be found.
```
new url https://nixos.org/download/

docs: fix README.md content link 404

---

frontend/src/Main.elm

I am often teaching people Nix, and then they bookmark search.nixos.org, as they find it really useful. Everything they need is on search.nixos.org, except for a reference to the NixOS wiki, which I inevitably have to refer them to.

frontend: add link to official NixOS Wiki
